Pandas practice

In [74]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:\\Users\\DEVARSHI\\Downloads\\archive (2).zip")
df

,title,genre,language,imdb_score,premiere,runtime,year
0,Notes for My Son,Drama,Spanish,6.3,11/24/2020,83,2020
1,"To Each, Her Own",Romantic comedy,French,5.3,6/24/2018,95,2018
2,The Lovebirds,Romantic comedy,English,6.1,5/22/2020,87,2020
3,The Perfection,Horror-thriller,English,6.1,5/24/2019,90,2019
4,Happy Anniversary,Romantic comedy,English,5.8,3/30/2018,78,2018
...,...,...,...,...,...,...,...
578,Rolling Thunder Revue: A bob Dylan Story by Ma...,Documentary,English,7.6,6/12/2019,144,2019
579,Freaks: You're One of Us,Supernatural drama,German,5.4,9/2/2020,92,2020
580,Squared Love,Romantic comedy,Polish,5.0,2/11/2021,102,2021
581,My Own Man,Documentary,English,6.4,12/13/2014,81,2014
582,Biggie: I Got a Story to Tell,Documentary,English,6.9,3/1/2021,97,2021

In [66]:
a = df.iloc[15]
print(a)

title             Polar
genre            Action
language        English
imdb_score          6.3
premiere      1/25/2019
runtime             118
year               2019
Name: 15, dtype: object

In [67]:
df.loc[5]

title         Why Did You Kill Me?
genre                  Documentary
language                   English
imdb_score                     5.6
premiere                 4/14/2021
runtime                         83
year                          2021
Name: 5, dtype: object

In [68]:
print(df.genre)

0                   Drama
1         Romantic comedy
2         Romantic comedy
3         Horror-thriller
4         Romantic comedy
              ...
578           Documentary
579    Supernatural drama
580       Romantic comedy
581           Documentary
582           Documentary
Name: genre, Length: 583, dtype: object

In [69]:
df.loc[(df.genre == 'Documentary')]

,title,genre,language,imdb_score,premiere,runtime,year
5,Why Did You Kill Me?,Documentary,English,5.6,4/14/2021,83,2021
7,Brene Brown: The Call to Courage,Documentary,English,7.7,4/19/2019,76,2019
11,El Pepe: A Supreme Life,Documentary,Spanish,7.1,12/27/2019,73,2019
12,Sky Ladder: The Art of Cai Guo-Qiang,Documentary,English/Mandarin,7.3,10/14/2016,79,2016
13,"Out of Many, One",Documentary,English,5.7,12/12/2018,34,2018
...,...,...,...,...,...,...,...
569,American Murder: The Family Next Door,Documentary,English,7.2,9/30/2020,82,2020
575,Long Shot,Documentary,English,7.4,9/29/2017,40,2017
578,Rolling Thunder Revue: A bob Dylan Story by Ma...,Documentary,English,7.6,6/12/2019,144,2019
581,My Own Man,Documentary,English,6.4,12/13/2014,81,2014
582,Biggie: I Got a Story to Tell,Documentary,English,6.9,3/1/2021,97,2021

In [70]:
df.groupby("runtime").max().sort_values('runtime',ascending=False)

,title,genre,language,imdb_score,premiere,year
runtime,,,,,,
209,The Irishman,Crime drama,English,7.8,11/27/2019,2019
155,Da 5 Bloods,War drama,English,6.5,6/12/2020,2020
153,Springsteen on Broadway,One-man show,English,8.5,12/16/2018,2018
151,The Forest of Love,Drama,Japanese,6.3,11/6/2020,2020
149,The Last Days of American Crime,Thriller,Hindi,7.6,7/31/2020,2020
...,...,...,...,...,...,...
11,Zion,Documentary,English,7.2,8/10/2018,2018
10,American Factory: A Conversation with the Obamas,Aftershow / Interview,English,5.2,8/21/2019,2019
9,Canvas,Animation / Short,English,6.5,12/11/2020,2020
7,Cops and Robbers,Animation / Short,English,6.9,12/28/2020,2020
4,Sol Levante,Anime / Short,English,4.7,4/2/2020,2020

In [71]:
# Sample data
data = {
    'A': [1, 2, None, 4],
    'B': [None, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data)

# Count non-null values in each column
column_counts = df.count()

print("Column Counts:")
print(column_counts)

Column Counts:
A    3
B    3
C    4
dtype: int64

In [72]:
# Count non-null values in each row
row_counts = df.count(axis=1)

print("\nRow Counts:")
print(row_counts)

Row Counts:
0    2
1    3
2    2
3    3
dtype: int64

In [75]:
df.groupby("imdb_score").min().sort_values('imdb_score',ascending=True).head(5)

,title,genre,language,premiere,runtime,year
imdb_score,,,,,,
2.5,Enter the Anime,Documentary,English/Japanese,8/5/2019,58,2019
2.6,Dark Forces,Science fiction/Drama,Italian,12/26/2019,79,2019
3.2,The Open House,Horror thriller,English,1/19/2018,94,2018
3.4,Kaali Khuhi,Mystery,Hindi,10/30/2020,90,2020
3.5,Drive,Action,Hindi,11/1/2019,147,2019

In [ ]:
df['language'].value_counts()

language
English                       401
Hindi                          32
Spanish                        31
French                         20
Italian                        14
Portuguese                     12
Indonesian                      9
Korean                          6
Japanese                        6
English/Spanish                 5
German                          5
Turkish                         5
Polish                          3
Dutch                           3
Marathi                         3
Filipino                        2
Thai                            2
English/Japanese                2
English/Hindi                   2
English/Mandarin                2
English/Korean                  1
Khmer/English/French            1
English/Akan                    1
Bengali                         1
English/Swedish                 1
English/Arabic                  1
English/Taiwanese/Mandarin      1
Norwegian                       1
Tamil                           1
English/Ukranian/Russian        1
Spanish/Catalan                 1
English/Russian                 1
Georgian                        1
Spanish/English                 1
Swedish                         1
Malay                           1
Thia/English                    1
Spanish/Basque                  1
Name: count, dtype: int64

In [ ]:
a =df.language.unique()
for i in a:
    print(i)

Spanish
French
English
Portuguese
English/Mandarin
English/Spanish
German
Italian
Korean
Thia/English
Hindi
Malay
Japanese
Marathi
Swedish
Indonesian
Dutch
Filipino
Spanish/English
English/Taiwanese/Mandarin
Georgian
English/Hindi
English/Russian
Spanish/Catalan
English/Ukranian/Russian
Tamil
Norwegian
Turkish
English/Arabic
Polish
English/Swedish
Bengali
English/Japanese
Thai
English/Korean
Khmer/English/French
English/Akan
Spanish/Basque

In [77]:
pd.Series(df['language'].unique()).count()

38